<?php
/*   _______________________________________
    |  Obfuscated by PMPR - Php Obfuscator  |
    |             684453f67f65f             |
    |_______________________________________|
*/
 namespace Pmpr\Module\ContentManagement\EditorialComment; use Pmpr\Common\Foundation\Interfaces\Constants; use Pmpr\Common\Foundation\Interfaces\IconInterface; use Pmpr\Module\ContentManagement\Container; use Pmpr\Module\ContentManagement\EditorialComment\Model\Flag; class EditorialComment extends Container { public function wigskegsqequoeks() { $this->qcsmikeggeemccuu('admin_head-edit.php', [$this, 'auiagqmymgqukauc'])->qcsmikeggeemccuu('load-post.php', [$this, 'eakamcqwssckiwcu'])->qcsmikeggeemccuu('manage_posts_custom_column', [$this, 'aqwsuqueaeyaemci'], 999, 2); } public function kgquecmsgcouyaya() { $this->cecaguuoecmccuse('manage_posts_columns', [$this, 'wakeowsaugqcigyg']); } public function mameiwsayuyquoeq() { MetaBox::symcgieuakksimmu(); if ($this->caokeucsksukesyo()->owicscwgeuqcqaig()->mcgoysmkqsqooceq(Ajax::PREFIX)) { Ajax::symcgieuakksimmu(); } } public function auiagqmymgqukauc() { ?>
        <style>
            .column-new_comment_flag {
                width: 2.2rem;
            }
        </style>
		<?php  } public function eakamcqwssckiwcu() { $gcqseksiskwueksc = $this->caokeucsksukesyo()->ayueggmoqeeukqmq()->iooowgsqoyqseyuu(); $ycoeoaakqyskgykq = $this->uwkmaywceaaaigwo()->issssuygyewuaswa()->qyeguewwsmosqcwc(); if ($gcqseksiskwueksc && $this->uwkmaywceaaaigwo()->issssuygyewuaswa()->yciaosuiyeieceug($ycoeoaakqyskgykq, 'edit_post', $gcqseksiskwueksc)) { $eqwoegegiamegqsm = $this->caokeucsksukesyo()->skckwsgymkimyuwo(); $seaoiakaugaiigwu = Flag::symcgieuakksimmu(); $cowcciqkqkmuagae = $seaoiakaugaiigwu->iekyeyicoyyawomk()->oqomcmyuuakigusk([$eqwoegegiamegqsm->megqywqeuquawkim(Constants::yauicucwkgqyygas, $ycoeoaakqyskgykq), $eqwoegegiamegqsm->megqywqeuquawkim(Constants::kqigmeickowqiiyy, $gcqseksiskwueksc)]); if ($cowcciqkqkmuagae) { $seaoiakaugaiigwu->gssiscqyqsacmeca()->wqikesawekycweoi($cowcciqkqkmuagae, [Constants::sugcoawcimusgaga => 1]); } else { $seaoiakaugaiigwu->gssiscqyqsacmeca()->gsegsiocqmsoayii([Constants::sugcoawcimusgaga => 1, Constants::yauicucwkgqyygas => $ycoeoaakqyskgykq, Constants::kqigmeickowqiiyy => $gcqseksiskwueksc]); } } } public function wakeowsaugqcigyg($wkkweuacukumqmya) : array { return $this->caokeucsksukesyo()->ywqgcuymeiswqyqc()->eyiwqmukkqeiqmmg($wkkweuacukumqmya, ['new_comment_flag' => ''], Constants::qescuiwgsyuikume); } public function aqwsuqueaeyaemci($qgoqiacsiccwoawi, $gcqseksiskwueksc = null) { if ($qgoqiacsiccwoawi === 'new_comment_flag' && Flag::symcgieuakksimmu()->yykseaikyyeckiii($gcqseksiskwueksc)) { echo $this->caokeucsksukesyo()->wgqqgewcmcemoewo()->cuoygaaeqeqcuggu(IconInterface::iqmuqqsmqeiyqkwu, ['class' => 'icon-sm icon-warning my-auto mr-2']); } } }
